/* flex/bison skeletons still emit the 'register' storage class, removed in
   C++17 (MSVC C5033, GCC/Clang -Wregister). It is generator boilerplate, not
   our code, so silence it for the whole translation unit. Keep this in sync
   with the matching block in the Read.l prologue (this file is regenerated). */
#if defined(_MSC_VER)
#pragma warning(disable : 5033)
#elif defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wregister"
#endif

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvsroot/classbuilder/Src/ClassBuilder/ClassBuilder/Read.l.cpp,v 1.1.1.1 2002/01/12 23:57:09 gunner Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifdef _WIN32
#include <io.h>
#else
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define READ_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define READ_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define READ_USE_PROTOS
#define READ_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define READ_USE_CONST
#endif


#ifndef READ_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef READ_USE_PROTOS
#define READ_PROTO(proto) proto
#else
#define READ_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define READ_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define READ_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN read_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define READ_START ((read_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define READ_STATE_EOF(state) (READ_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define READ_NEW_FILE readrestart( readin )

#define READ_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define READ_BUF_SIZE 16384

typedef struct read_buffer_state *READ_BUFFER_STATE;

extern int readleng;
extern FILE *readin, *readout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int readwrap READ_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		readless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the readless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define readless(n) \
	do \
		{ \
		/* Undo effects of setting up readtext. */ \
		*read_cp = read_hold_char; \
		read_c_buf_p = read_cp = read_bp + n - READ_MORE_ADJ; \
		READ_DO_BEFORE_ACTION; /* set up readtext again */ \
		} \
	while ( 0 )

#define unput(c) readunput( c, readtext_ptr )


struct read_buffer_state
	{
	FILE *read_input_file;

	char *read_ch_buf;		/* input buffer */
	char *read_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int read_buf_size;

	/* Number of characters read into read_ch_buf, not including EOB
	 * characters.
	 */
	int read_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int read_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int read_fill_buffer;

	int read_buffer_status;
#define READ_BUFFER_NEW 0
#define READ_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as READ_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via readrestart()), so that the user can continue scanning by
	 * just pointing readin at a new input file.
	 */
#define READ_BUFFER_EOF_PENDING 2
	};

static READ_BUFFER_STATE read_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define READ_CURRENT_BUFFER read_current_buffer


/* read_hold_char holds the character lost when readtext is formed. */
static char read_hold_char;

static int read_n_chars;		/* number of characters read into read_ch_buf */


int readleng;

/* Points to current character in buffer. */
static char *read_c_buf_p = (char *) 0;
static int read_init = 1;		/* whether we need to initialize */
static int read_start = 0;	/* start state number */

/* Flag which is used to allow readwrap()'s to do buffer switches
 * instead of setting up a fresh readin.  A bit of a hack ...
 */
static int read_did_buffer_switch_on_eof;

static void readunput READ_PROTO(( int c, char *buf_ptr ));
void readrestart READ_PROTO(( FILE *input_file ));
void read_switch_to_buffer READ_PROTO(( READ_BUFFER_STATE new_buffer ));
void read_load_buffer_state READ_PROTO(( void ));
READ_BUFFER_STATE read_create_buffer READ_PROTO(( FILE *file, int size ));
void read_delete_buffer READ_PROTO(( READ_BUFFER_STATE b ));
void read_init_buffer READ_PROTO(( READ_BUFFER_STATE b, FILE *file ));

static int read_start_stack_ptr = 0;
static int read_start_stack_depth = 0;
static int *read_start_stack = 0;
static void read_push_state READ_PROTO(( int new_state ));
static void read_pop_state READ_PROTO(( void ));
static int read_top_state READ_PROTO(( void ));

#ifndef __BORLANDC__
static void *read_flex_alloc READ_PROTO(( unsigned int ));
static void *read_flex_realloc READ_PROTO(( void *, unsigned int ));
#else /* __BORLANDC__ */
static void *read_flex_alloc READ_PROTO(( size_t ));
static void *read_flex_realloc READ_PROTO(( void *, size_t ));
#endif /* __BORLANDC__ */
static void read_flex_free READ_PROTO(( void * ));

#define read_new_buffer read_create_buffer

#define INITIAL 0
#define normal 1
#define comment 2
#define user1 3
#define user2 4
#define user3 5
#define note 6
#define code 7
#define init 8
#define declaration 9
typedef unsigned char READ_CHAR;
typedef int read_state_type;
FILE *readin = (FILE *) 0, *readout = (FILE *) 0;
extern char *readtext;
#define readtext_ptr readtext

#ifndef readtext_ptr
static void read_flex_strncpy READ_PROTO(( char *, const char *, int ));
#endif

#ifdef __cplusplus
static int readinput READ_PROTO(( void ));
#else
static int input READ_PROTO(( void ));
#endif

static read_state_type read_get_previous_state READ_PROTO(( void ));
static read_state_type read_try_NUL_trans READ_PROTO(( read_state_type current_state ));
static int read_get_next_buffer READ_PROTO(( void ));
static void read_fatal_error READ_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up readtext.
 */
#define READ_DO_BEFORE_ACTION \
	readtext_ptr = read_bp; \
	readleng = read_cp - read_bp; \
	read_hold_char = *read_cp; \
	*read_cp = '\0'; \
	read_c_buf_p = read_cp;

#define READ_END_OF_BUFFER 37
static const short int read_accept[205] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       37,   36,    1,   35,   34,    1,   35,   35,    3,    4,
        1,    3,    7,    8,    1,    7,   11,   12,    1,   11,
       15,   16,    1,   15,   23,   24,    1,   23,   31,   32,
        1,   31,   27,   28,    1,   27,   19,   20,    1,   19,
        2,    0,    0,    5,    0,    0,    0,   25,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   22,    0,    0,   26,    0,    0,    0,    0,    0,
        0,    0,   33,    0,    0,    0,    0,    0,   30,    0,
        0,    0,    0,    0,   29,    0,    0,    0,    0,    9,
       13,   17,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,   10,    0,   14,    0,    0,
        0,    0,    0,    0,    0,    0,   21,    0,   21,    0,

        0,   18,    0,    0
    } ;

static const int read_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    5,    6,    7,    8,
        9,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    1,    1,   10,   11,    1,   12,   13,   14,    1,
        1,    1,   15,    1,    1,   16,    1,   17,   18,    1,
        1,   19,   20,   21,   22,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   23,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   24,    1,   25,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int read_meta[26] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const short int read_base[229] =
    {   0,
      276,  275,    0,   23,    4,    7,   10,   14,   18,   27,
       31,   35,   39,   42,   46,   48,   50,   52,   54,   58,
      277,  280,  280,  280,  280,  280,   60,  271,  280,  280,
      280,  270,  280,  280,  280,  269,  280,  280,  280,  268,
      280,  280,  280,  267,  280,  280,  280,  266,  280,  280,
      280,  265,  280,  280,  280,  264,  280,  280,  280,  263,
      257,  256,  260,  280,  254,  253,  252,  280,  256,  255,
      249,  241,    7,  247,  242,  241,  240,  243,  242,  237,
      232,  232,  227,  235,  229,  228,  227,  231,  230,  224,
      219,  224,  227,  219,  223,  222,  221,  215,  214,  218,

      216,  208,  209,  214,  203,  202,  201,  210,  209,  198,
      197,  196,  197,  203,  194,  193,  192,  199,  198,  198,
        0,    0,  187,  186,  188,  187,  186,  182,  181,  189,
       75,   83,   45,    0,  188,  187,  186,    0,    0,  187,
      196,  280,   91,  195,  280,   99,  182,  175,  107,  175,
      174,  133,    0,  115,  135,  138,  130,  141,  280,  123,
      135,  128,  126,  132,  280,  131,  117,  111,  107,  280,
      280,  280,  101,  108,   61,  107,   93,  109,  108,  102,
       82,   91,   94,  280,   93,  280,   92,  280,   73,   66,
       68,   65,   62,   60,   52,   55,    0,   43,    0,  139,

       60,  280,  147,  280,  156,  158,  160,  162,  164,  166,
      168,  170,  172,  174,   37,   33,  176,  178,   29,   16,
       12,  180,  182,  184,  186,  188,    2,  190
    } ;

static const short int read_def[229] =
    {   0,
      205,  205,  206,  206,  207,  207,  208,  208,  209,  209,
      210,  210,  211,  211,  212,  212,  213,  213,  214,  214,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      215,  216,  204,  204,  204,  204,  204,  204,  204,  204,
      217,  218,  204,  219,  204,  204,  204,  220,  221,  204,
      217,  204,  217,  218,  204,  218,  204,  204,  222,  204,
      204,  204,  220,  223,  204,  204,  204,  222,  204,  222,
      204,  204,  204,  223,  204,  223,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  224,  225,  226,
      204,  204,  224,  204,  225,  204,  226,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  227,  204,  227,  228,

      228,  204,  228,    0,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204
    } ;

static const short int read_nxt[306] =
    {   0,
      204,   25,   26,  199,   27,   30,   31,   32,   30,   31,
       32,   34,   35,  154,   36,   34,   35,  153,   36,   38,
       39,   82,   40,   28,   25,   26,   83,   27,   38,   39,
      149,   40,   42,   43,  132,   44,   42,   43,  131,   44,
       46,   47,   48,   46,   47,   48,   28,   50,   51,   50,
       51,   54,   55,   54,   55,   58,   59,  147,   60,   58,
       59,  202,   60,   61,   62,  200,  148,  178,  179,  180,
       52,  198,   52,   56,  197,   56,  142,  196,  195,  194,
      143,  143,  143,  143,  145,  193,  192,  191,  146,  146,
      146,  146,  142,  188,  186,  184,  143,  143,  143,  143,

      145,  190,  189,  188,  146,  146,  146,  146,  159,  186,
      184,  182,  160,  160,  160,  160,  165,  181,  177,  176,
      166,  166,  166,  166,  159,  175,  174,  173,  160,  160,
      160,  160,  165,  165,  172,  171,  166,  166,  166,  166,
      202,  170,  159,  169,  203,  203,  203,  203,  202,  168,
      167,  163,  203,  203,  203,  203,   22,   22,   24,   24,
       29,   29,   33,   33,   37,   37,   41,   41,   45,   45,
       49,   49,   53,   53,   57,   57,  141,  141,  144,  144,
      158,  158,  164,  164,  183,  183,  185,  185,  187,  187,
      201,  201,  162,  161,  157,  156,  145,  142,  155,  152,

      151,  150,  140,  139,  138,  137,  136,  135,  134,  133,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   81,   80,   79,
       78,   77,   76,   75,   74,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,  204,   23,   23,   21,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204
    } ;

static const short int read_chk[306] =
    {   0,
        0,    3,    3,  227,    3,    5,    5,    5,    6,    6,
        6,    7,    7,  221,    7,    8,    8,  220,    8,    9,
        9,   73,    9,    3,    4,    4,   73,    4,   10,   10,
      219,   10,   11,   11,  216,   11,   12,   12,  215,   12,
       13,   13,   13,   14,   14,   14,    4,   15,   15,   16,
       16,   17,   17,   18,   18,   19,   19,  133,   19,   20,
       20,  201,   20,   27,   27,  198,  133,  175,  175,  175,
       15,  196,   16,   17,  195,   18,  131,  194,  193,  192,
      131,  131,  131,  131,  132,  191,  190,  189,  132,  132,
      132,  132,  143,  187,  185,  183,  143,  143,  143,  143,

      146,  182,  181,  180,  146,  146,  146,  146,  149,  179,
      178,  177,  149,  149,  149,  149,  154,  176,  174,  173,
      154,  154,  154,  154,  160,  169,  168,  167,  160,  160,
      160,  160,  166,  164,  163,  162,  166,  166,  166,  166,
      200,  161,  158,  157,  200,  200,  200,  200,  203,  156,
      155,  152,  203,  203,  203,  203,  205,  205,  206,  206,
      207,  207,  208,  208,  209,  209,  210,  210,  211,  211,
      212,  212,  213,  213,  214,  214,  217,  217,  218,  218,
      222,  222,  223,  223,  224,  224,  225,  225,  226,  226,
      228,  228,  151,  150,  148,  147,  144,  141,  140,  137,

      136,  135,  130,  129,  128,  127,  126,  125,  124,  123,
      120,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   72,   71,   70,
       69,   67,   66,   65,   63,   62,   61,   60,   56,   52,
       48,   44,   40,   36,   32,   28,   21,    2,    1,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204
    } ;

static read_state_type read_last_accepting_state;
static char *read_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define readmore() readmore_used_but_not_detected
#define READ_MORE_ADJ 0
char *readtext;
# line 1 "Read.l"
# line 2 "Read.l"
#include <stdlib.h>
#include <string.h>

#include /**/ "Read.y.h"

char readline[4096];
char readlineUser3[4096];
char readinterface[4096];
int readlineleng = 0;
int readlineno = 1;
int readindex = 0;
int readinterfaceIndex = 0;

enum ModeType {
    NormalMode = 0,
    CommentMode,
    User1Mode,
    User2Mode,
    User3Mode,
    NoteMode,
    CodeMode,
    InitMode,
	DeclarationMode
};

int readmode = 0;

#define DEFAULT {\
    readline[readindex++] = readtext[0];\
    readline[readindex] = '\0';\
}

#define NEWLINE {\
    readline[readindex++] = '\015';\
    readline[readindex++] = '\012';\
    readline[readindex++] = '\0';\
    readlval.sval = readline;\
    readlineno++;\
    readindex = 0;\
    return LINE;\
}

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef READ_MALLOC_DECL
READ_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef READ_READ_BUF_SIZE
#define READ_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( readtext, readleng, 1, readout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or READ_NULL,
 * is returned in "result".
 */
#ifndef READ_INPUT
#define READ_INPUT(buf,result,max_size) \
	if ( read_current_buffer->read_is_interactive ) \
		{ \
		int c = getc( readin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, readin )) == 0) \
		  && ferror( readin ) ) \
		READ_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "readterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef readterminate
#define readterminate() return READ_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef READ_START_STACK_INCR
#define READ_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef READ_FATAL_ERROR
#define READ_FATAL_ERROR(msg) read_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef READ_DECL
#define READ_DECL int readlex READ_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after readtext and readleng
 * have been set up.
 */
#ifndef READ_USER_ACTION
#define READ_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef READ_BREAK
#define READ_BREAK break;
#endif

READ_DECL
	{
	register read_state_type read_current_state;
	register char *read_cp, *read_bp;
	register int read_act;

# line 62 "Read.l"

    {
        switch (ModeType(readmode))
        {
        case NormalMode:
            BEGIN normal;
            break;
        case CommentMode:
            BEGIN comment;
            break;
        case User1Mode:
            BEGIN user1;
            break;
        case User3Mode:
            BEGIN user3;
            break;
        case User2Mode:
            BEGIN user2;
            break;
        case NoteMode:
            BEGIN note;
            break;
        case CodeMode:
            BEGIN code;
            break;
        case InitMode:
            BEGIN init;
            break;
		case DeclarationMode:
		    BEGIN declaration;
			break;
        }
    }

	if ( read_init )
		{
#ifdef READ_USER_INIT
		READ_USER_INIT;
#endif

		if ( ! read_start )
			read_start = 1;	/* first start state */

		if ( ! readin )
			readin = stdin;

		if ( ! readout )
			readout = stdout;

		if ( read_current_buffer )
			read_init_buffer( read_current_buffer, readin );
		else
			read_current_buffer =
				read_create_buffer( readin, READ_BUF_SIZE );

		read_load_buffer_state();

		read_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		read_cp = read_c_buf_p;

		/* Support of readtext. */
		*read_cp = read_hold_char;

		/* read_bp points to the position in read_ch_buf of the start of
		 * the current run.
		 */
		read_bp = read_cp;

		read_current_state = read_start;
read_match:
		do
			{
			register READ_CHAR read_c = read_ec[READ_SC_TO_UI(*read_cp)];
			if ( read_accept[read_current_state] )
				{
				read_last_accepting_state = read_current_state;
				read_last_accepting_cpos = read_cp;
				}
			while ( read_chk[read_base[read_current_state] + read_c] != read_current_state )
				{
				read_current_state = (int) read_def[read_current_state];
				if ( read_current_state >= 205 )
					read_c = read_meta[(unsigned int) read_c];
				}
			read_current_state = read_nxt[read_base[read_current_state] + (unsigned int) read_c];
			++read_cp;
			}
		while ( read_base[read_current_state] != 280 );

read_find_action:
		read_act = read_accept[read_current_state];

		READ_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( read_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of READ_DO_BEFORE_ACTION */
			*read_cp = read_hold_char;
			read_cp = read_last_accepting_cpos;
			read_current_state = read_last_accepting_state;
			goto read_find_action;

case 1:
READ_USER_ACTION
# line 95 "Read.l"
;
	READ_BREAK
case 2:
READ_USER_ACTION
# line 96 "Read.l"
{
    readindex = 0;
    readline[readindex++] = '/';
    readline[readindex++] = '*';
    BEGIN comment;
    readmode = CommentMode;
    return START_COMMENT;
}
	READ_BREAK
case 3:
READ_USER_ACTION
# line 104 "Read.l"
DEFAULT
	READ_BREAK
case 4:
READ_USER_ACTION
# line 105 "Read.l"
NEWLINE
	READ_BREAK
case 5:
READ_USER_ACTION
# line 106 "Read.l"
{
    readline[readindex++] = '*';
    readline[readindex++] = '/';
    readline[readindex++] = '\0';
    readlval.sval = readline;
    readindex = 0;
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_COMMENT;
}
	READ_BREAK
case 6:
READ_USER_ACTION
# line 118 "Read.l"
{
    readlineno++;
    readindex = 0;
    BEGIN user1;
    readmode = User1Mode;
    return START_USER1;
}
	READ_BREAK
case 7:
READ_USER_ACTION
# line 125 "Read.l"
DEFAULT
	READ_BREAK
case 8:
READ_USER_ACTION
# line 126 "Read.l"
NEWLINE
	READ_BREAK
case 9:
READ_USER_ACTION
# line 127 "Read.l"
{
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_USER1;
}
	READ_BREAK
case 10:
READ_USER_ACTION
# line 134 "Read.l"
{
    readlineno++;
    readindex = 0;
    BEGIN user2;
    readmode = User2Mode;
    return START_USER2;
}
	READ_BREAK
case 11:
READ_USER_ACTION
# line 141 "Read.l"
DEFAULT
	READ_BREAK
case 12:
READ_USER_ACTION
# line 142 "Read.l"
NEWLINE
	READ_BREAK
case 13:
READ_USER_ACTION
# line 143 "Read.l"
{
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_USER2;
}
	READ_BREAK
case 14:
READ_USER_ACTION
# line 150 "Read.l"
{
    readlineno++;
    readindex = 0;
    BEGIN user3;
    readmode = User3Mode;
    return START_USER3;
}
	READ_BREAK
case 15:
READ_USER_ACTION
# line 157 "Read.l"
DEFAULT
	READ_BREAK
case 16:
READ_USER_ACTION
# line 158 "Read.l"
NEWLINE
	READ_BREAK
case 17:
READ_USER_ACTION
# line 159 "Read.l"
{
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_USER3;
}
	READ_BREAK
case 18:
READ_USER_ACTION
# line 166 "Read.l"
{
    readlineno++;
    readindex = 0;
    readlval.ival = atoi(readtext+21);
    BEGIN declaration;
    readmode = DeclarationMode;
    return START_DECLARATION;
}
	READ_BREAK
case 19:
READ_USER_ACTION
# line 174 "Read.l"
DEFAULT
	READ_BREAK
case 20:
READ_USER_ACTION
# line 175 "Read.l"
NEWLINE
	READ_BREAK
case 21:
READ_USER_ACTION
# line 176 "Read.l"
{
    readlval.ival = atoi(readtext+19);
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_DECLARATION;
}
	READ_BREAK
case 22:
READ_USER_ACTION
# line 184 "Read.l"
{
    readlineno++;
    readindex = 0;
    readlval.ival = atoi(readtext+8);
    BEGIN note;
    readmode = NoteMode;
    return START_NOTE;
}
	READ_BREAK
case 23:
READ_USER_ACTION
# line 192 "Read.l"
DEFAULT
	READ_BREAK
case 24:
READ_USER_ACTION
# line 193 "Read.l"
NEWLINE
	READ_BREAK
case 25:
READ_USER_ACTION
# line 194 "Read.l"
{
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_NOTE;
}
	READ_BREAK
case 26:
READ_USER_ACTION
# line 201 "Read.l"
{
    readlineno++;
    readindex = 0;
    readlval.ival = atoi(readtext+8);
    BEGIN init;
    readmode = InitMode;
    return START_INIT;
}
	READ_BREAK
case 27:
READ_USER_ACTION
# line 209 "Read.l"
DEFAULT
	READ_BREAK
case 28:
READ_USER_ACTION
# line 210 "Read.l"
NEWLINE
	READ_BREAK
case 29:
READ_USER_ACTION
# line 211 "Read.l"
{
    readlval.ival = atoi(readtext+9);
    BEGIN code;
    readmode = CodeMode;
    return START_CODE;
}
	READ_BREAK
case 30:
READ_USER_ACTION
# line 218 "Read.l"
{
    readlineno++;
    readindex = 0;
    readlval.ival = atoi(readtext+9);
    BEGIN code;
    readmode = CodeMode;
    return START_CODE;
}
	READ_BREAK
case 31:
READ_USER_ACTION
# line 226 "Read.l"
DEFAULT
	READ_BREAK
case 32:
READ_USER_ACTION
# line 227 "Read.l"
NEWLINE
	READ_BREAK
case 33:
READ_USER_ACTION
# line 228 "Read.l"
{
    readlval.ival = atoi(readtext+9);
    BEGIN normal;
    readmode = NormalMode;
	readinterfaceIndex = 0;
    return END_CODE;
}
	READ_BREAK
case 34:
READ_USER_ACTION
# line 236 "Read.l"
{
    readlineno++;
    readinterface[readinterfaceIndex] = '\015';
	readinterfaceIndex = (readinterfaceIndex+1)%4096;
    readinterface[readinterfaceIndex] = '\012';
	readinterfaceIndex = (readinterfaceIndex+1)%4096;
    readinterface[readinterfaceIndex] = '\0';
}
	READ_BREAK
case 35:
READ_USER_ACTION
# line 244 "Read.l"
{
    readinterface[readinterfaceIndex] = readtext[0];
	readinterfaceIndex = (readinterfaceIndex+1)%4096;
    readinterface[readinterfaceIndex] = '\0';
}
	READ_BREAK
case 36:
READ_USER_ACTION
# line 249 "Read.l"
ECHO;
	READ_BREAK
case READ_STATE_EOF(INITIAL):
case READ_STATE_EOF(normal):
case READ_STATE_EOF(comment):
case READ_STATE_EOF(user1):
case READ_STATE_EOF(user2):
case READ_STATE_EOF(user3):
case READ_STATE_EOF(note):
case READ_STATE_EOF(code):
case READ_STATE_EOF(init):
case READ_STATE_EOF(declaration):
	readterminate();

	case READ_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int read_amount_of_matched_text = read_cp - readtext_ptr - 1;

		/* Undo the effects of READ_DO_BEFORE_ACTION. */
		*read_cp = read_hold_char;

		if ( read_current_buffer->read_buffer_status == READ_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed readin at a new source and called
			 * readlex().  If so, then we have to assure
			 * consistency between read_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			read_n_chars = read_current_buffer->read_n_chars;
			read_current_buffer->read_input_file = readin;
			read_current_buffer->read_buffer_status = READ_BUFFER_NORMAL;
			}

		/* Note that here we test for read_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since read_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( read_c_buf_p <= &read_current_buffer->read_ch_buf[read_n_chars] )
			{ /* This was really a NUL. */
			read_state_type read_next_state;

			read_c_buf_p = readtext_ptr + read_amount_of_matched_text;

			read_current_state = read_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * read_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			read_next_state = read_try_NUL_trans( read_current_state );

			read_bp = readtext_ptr + READ_MORE_ADJ;

			if ( read_next_state )
				{
				/* Consume the NUL. */
				read_cp = ++read_c_buf_p;
				read_current_state = read_next_state;
				goto read_match;
				}

			else
				{
							read_cp = read_c_buf_p;
				goto read_find_action;
				}
			}

		else switch ( read_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				read_did_buffer_switch_on_eof = 0;

				if ( readwrap() )
					{
					/* Note: because we've taken care in
					 * read_get_next_buffer() to have set up
					 * readtext, we can now set up
					 * read_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * READ_NULL, it'll still work - another
					 * READ_NULL will get returned.
					 */
					read_c_buf_p = readtext_ptr + READ_MORE_ADJ;

					read_act = READ_STATE_EOF(READ_START);
					goto do_action;
					}

				else
					{
					if ( ! read_did_buffer_switch_on_eof )
						READ_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				read_c_buf_p =
					readtext_ptr + read_amount_of_matched_text;

				read_current_state = read_get_previous_state();

				read_cp = read_c_buf_p;
				read_bp = readtext_ptr + READ_MORE_ADJ;
				goto read_match;

			case EOB_ACT_LAST_MATCH:
				read_c_buf_p =
				&read_current_buffer->read_ch_buf[read_n_chars];

				read_current_state = read_get_previous_state();

				read_cp = read_c_buf_p;
				read_bp = readtext_ptr + READ_MORE_ADJ;
				goto read_find_action;
			}
		break;
		}

	default:
		READ_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of readlex */


/* read_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int read_get_next_buffer()
	{
	register char *dest = read_current_buffer->read_ch_buf;
	register char *source = readtext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( read_c_buf_p > &read_current_buffer->read_ch_buf[read_n_chars + 1] )
		READ_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( read_current_buffer->read_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( read_c_buf_p - readtext_ptr - READ_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = read_c_buf_p - readtext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( read_current_buffer->read_buffer_status == READ_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		read_n_chars = 0;

	else
		{
		int num_to_read =
			read_current_buffer->read_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef READ_USES_REJECT
			READ_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			READ_BUFFER_STATE b = read_current_buffer;

			int read_c_buf_p_offset = read_c_buf_p - b->read_ch_buf;

			b->read_buf_size *= 2;
			b->read_ch_buf = (char *)
				read_flex_realloc( (void *) b->read_ch_buf,
						 b->read_buf_size );

			if ( ! b->read_ch_buf )
				READ_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			read_c_buf_p = &b->read_ch_buf[read_c_buf_p_offset];

			num_to_read = read_current_buffer->read_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > READ_READ_BUF_SIZE )
			num_to_read = READ_READ_BUF_SIZE;

		/* Read in more data. */
		READ_INPUT( (&read_current_buffer->read_ch_buf[number_to_move]),
			read_n_chars, num_to_read );
		}

	if ( read_n_chars == 0 )
		{
		if ( number_to_move - READ_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			readrestart( readin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			read_current_buffer->read_buffer_status =
				READ_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	read_n_chars += number_to_move;
	read_current_buffer->read_ch_buf[read_n_chars] = READ_END_OF_BUFFER_CHAR;
	read_current_buffer->read_ch_buf[read_n_chars + 1] = READ_END_OF_BUFFER_CHAR;

	/* readtext begins at the second character in read_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * read_get_previous_state() will have with '^' rules active.
	 */

	readtext_ptr = &read_current_buffer->read_ch_buf[1];

	return ret_val;
	}


/* read_get_previous_state - get the state just before the EOB char was reached */

static read_state_type read_get_previous_state()
	{
	register read_state_type read_current_state;
	register char *read_cp;

	read_current_state = read_start;

	for ( read_cp = readtext_ptr + READ_MORE_ADJ; read_cp < read_c_buf_p; ++read_cp )
		{
		register READ_CHAR read_c = (*read_cp ? read_ec[READ_SC_TO_UI(*read_cp)] : 1);
		if ( read_accept[read_current_state] )
			{
			read_last_accepting_state = read_current_state;
			read_last_accepting_cpos = read_cp;
			}
		while ( read_chk[read_base[read_current_state] + read_c] != read_current_state )
			{
			read_current_state = (int) read_def[read_current_state];
			if ( read_current_state >= 205 )
				read_c = read_meta[(unsigned int) read_c];
			}
		read_current_state = read_nxt[read_base[read_current_state] + (unsigned int) read_c];
		}

	return read_current_state;
	}


/* read_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = read_try_NUL_trans( current_state );
 */

#ifdef READ_USE_PROTOS
static read_state_type read_try_NUL_trans( read_state_type read_current_state )
#else
static read_state_type read_try_NUL_trans( read_current_state )
read_state_type read_current_state;
#endif
	{
	register int read_is_jam;
	register char *read_cp = read_c_buf_p;

	register READ_CHAR read_c = 1;
	if ( read_accept[read_current_state] )
		{
		read_last_accepting_state = read_current_state;
		read_last_accepting_cpos = read_cp;
		}
	while ( read_chk[read_base[read_current_state] + read_c] != read_current_state )
		{
		read_current_state = (int) read_def[read_current_state];
		if ( read_current_state >= 205 )
			read_c = read_meta[(unsigned int) read_c];
		}
	read_current_state = read_nxt[read_base[read_current_state] + (unsigned int) read_c];
	read_is_jam = (read_current_state == 204);

	return read_is_jam ? 0 : read_current_state;
	}


#ifdef READ_USE_PROTOS
static void readunput( int c, register char *read_bp )
#else
static void readunput( c, read_bp )
int c;
register char *read_bp;
#endif
	{
	register char *read_cp = read_c_buf_p;

	/* undo effects of setting up readtext */
	*read_cp = read_hold_char;

	if ( read_cp < read_current_buffer->read_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = read_n_chars + 2;
		register char *dest = &read_current_buffer->read_ch_buf[
					read_current_buffer->read_buf_size + 2];
		register char *source =
				&read_current_buffer->read_ch_buf[number_to_move];

		while ( source > read_current_buffer->read_ch_buf )
			*--dest = *--source;

		read_cp += dest - source;
		read_bp += dest - source;
		read_n_chars = read_current_buffer->read_buf_size;

		if ( read_cp < read_current_buffer->read_ch_buf + 2 )
			READ_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( read_cp > read_bp && read_cp[-1] == '\n' )
		read_cp[-2] = '\n';

	*--read_cp = (char) c;


	/* Note: the formal parameter *must* be called "read_bp" for this
	 * macro to now work correctly.
	 */
	READ_DO_BEFORE_ACTION; /* set up readtext again */
	}


#ifdef __cplusplus
static int readinput()
#else
static int input()
#endif
	{
	int c;

	*read_c_buf_p = read_hold_char;

	if ( *read_c_buf_p == READ_END_OF_BUFFER_CHAR )
		{
		/* read_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( read_c_buf_p < &read_current_buffer->read_ch_buf[read_n_chars] )
			/* This was really a NUL. */
			*read_c_buf_p = '\0';

		else
			{ /* need more input */
			readtext_ptr = read_c_buf_p;
			++read_c_buf_p;

			switch ( read_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( readwrap() )
						{
						read_c_buf_p =
						readtext_ptr + READ_MORE_ADJ;
						return EOF;
						}

					READ_NEW_FILE;
#ifdef __cplusplus
					return readinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					read_c_buf_p = readtext_ptr + READ_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					READ_FATAL_ERROR(
					"unexpected last match in readinput()" );
#else
					READ_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) read_c_buf_p;	/* cast for 8-bit char's */
	*read_c_buf_p = '\0';	/* preserve readtext */
	read_hold_char = *++read_c_buf_p;

	return c;
	}


#ifdef READ_USE_PROTOS
void readrestart( FILE *input_file )
#else
void readrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! read_current_buffer )
		read_current_buffer = read_create_buffer( readin, READ_BUF_SIZE );

	read_init_buffer( read_current_buffer, input_file );
	read_load_buffer_state();
	}


#ifdef READ_USE_PROTOS
void read_switch_to_buffer( READ_BUFFER_STATE new_buffer )
#else
void read_switch_to_buffer( new_buffer )
READ_BUFFER_STATE new_buffer;
#endif
	{
	if ( read_current_buffer == new_buffer )
		return;

	if ( read_current_buffer )
		{
		/* Flush out information for old buffer. */
		*read_c_buf_p = read_hold_char;
		read_current_buffer->read_buf_pos = read_c_buf_p;
		read_current_buffer->read_n_chars = read_n_chars;
		}

	read_current_buffer = new_buffer;
	read_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (readwrap()) processing, but the only time this flag
	 * is looked at is after readwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	read_did_buffer_switch_on_eof = 1;
	}


#ifdef READ_USE_PROTOS
void read_load_buffer_state( void )
#else
void read_load_buffer_state()
#endif
	{
	read_n_chars = read_current_buffer->read_n_chars;
	readtext_ptr = read_c_buf_p = read_current_buffer->read_buf_pos;
	readin = read_current_buffer->read_input_file;
	read_hold_char = *read_c_buf_p;
	}


#ifdef READ_USE_PROTOS
READ_BUFFER_STATE read_create_buffer( FILE *file, int size )
#else
READ_BUFFER_STATE read_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	READ_BUFFER_STATE b;

	b = (READ_BUFFER_STATE) read_flex_alloc( sizeof( struct read_buffer_state ) );

	if ( ! b )
		READ_FATAL_ERROR( "out of dynamic memory in read_create_buffer()" );

	b->read_buf_size = size;

	/* read_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->read_ch_buf = (char *) read_flex_alloc( b->read_buf_size + 2 );

	if ( ! b->read_ch_buf )
		READ_FATAL_ERROR( "out of dynamic memory in read_create_buffer()" );

	read_init_buffer( b, file );

	return b;
	}


#ifdef READ_USE_PROTOS
void read_delete_buffer( READ_BUFFER_STATE b )
#else
void read_delete_buffer( b )
READ_BUFFER_STATE b;
#endif
	{
	if ( b == read_current_buffer )
		read_current_buffer = (READ_BUFFER_STATE) 0;

	read_flex_free( (void *) b->read_ch_buf );
	read_flex_free( (void *) b );
	}


#ifdef READ_USE_PROTOS
void read_init_buffer( READ_BUFFER_STATE b, FILE *file )
#else
void read_init_buffer( b, file )
READ_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->read_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->read_ch_buf[0] = '\n';
	b->read_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->read_ch_buf[1] = READ_END_OF_BUFFER_CHAR;
	b->read_ch_buf[2] = READ_END_OF_BUFFER_CHAR;

	b->read_buf_pos = &b->read_ch_buf[1];

	b->read_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->read_fill_buffer = 1;

	b->read_buffer_status = READ_BUFFER_NEW;
	}


#ifdef READ_USE_PROTOS
static void read_push_state( int new_state )
#else
static void read_push_state( new_state )
int new_state;
#endif
	{
	if ( read_start_stack_ptr >= read_start_stack_depth )
		{
		int new_size;

		read_start_stack_depth += READ_START_STACK_INCR;
		new_size = read_start_stack_depth * sizeof( int );

		if ( ! read_start_stack )
			read_start_stack = (int *) read_flex_alloc( new_size );

		else
			read_start_stack = (int *) read_flex_realloc(
					(void *) read_start_stack, new_size );

		if ( ! read_start_stack )
			READ_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	read_start_stack[read_start_stack_ptr++] = READ_START;

	BEGIN(new_state);
	}


static void read_pop_state()
	{
	if ( --read_start_stack_ptr < 0 )
		READ_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(read_start_stack[read_start_stack_ptr]);
	}


static int read_top_state()
	{
	return read_start_stack[read_start_stack_ptr - 1];
	}


#ifdef READ_USE_PROTOS
static void read_fatal_error( const char msg[] )
#else
static void read_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine readless() so it works in section 3 code. */

#undef readless
#define readless(n) \
	do \
		{ \
		/* Undo effects of setting up readtext. */ \
		readtext[readleng] = read_hold_char; \
		read_c_buf_p = readtext + n - READ_MORE_ADJ; \
		read_hold_char = *read_c_buf_p; \
		*read_c_buf_p = '\0'; \
		readleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef readtext_ptr
#ifdef READ_USE_PROTOS
static void read_flex_strncpy( char *s1, const char *s2, int n )
#else
static void read_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef READ_USE_PROTOS
static void *read_flex_alloc( unsigned int size )
#else
static void *read_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef READ_USE_PROTOS
static void *read_flex_realloc( void *ptr, unsigned int size )
#else
static void *read_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef READ_USE_PROTOS
static void read_flex_free( void *ptr )
#else
static void read_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 249 "Read.l"


int readwrap( )
{
	if (readmode == User3Mode && readindex)
	{
		readline[readindex] = '\0';
		strcpy(readlineUser3, readline);
	}
	else
		readlineUser3[0] = '\0';

    strcpy( readline, "" );
    readlineno = 1;
    readindex = 0;
    readmode = 0;
    
    return 1;
}

