# flip_int_bool_flags.ps1 -- the "others" half of the int IsXxx->bool sweep.
# Flips the model's int BOOLEAN-FLAG members (+ their getter return / setter arg)
# and the remaining int predicate METHODS to bool, via the pipe API.
#
# Wire-safe: CbArchive serialises bool as a 4-byte int (== the old int), so
# serialized members' .cbz / generated byte stream is UNCHANGED (see
# convert_BOOL_to_bool.ps1 / CbSerialize.h).
#
# The member list excludes confirmed NON-bools verified by code usage:
#   Class::_flag (tri-state 0/1/2), _multiPage (1<<exp), _verbosity (level),
#   _last (undo level), and all counts/sizes/coords/ids/order/icon/version.
#
#   pwsh tools/flip_int_bool_flags.ps1            # dry run (prints the plan)
#   pwsh tools/flip_int_bool_flags.ps1 -Apply     # do it
#
# After -Apply:  save_cb + write_source, apply the staged bool iterator macros
# (tools/isx_bool_macros/*.bool.h -> Include/), then rebuild.

param([switch]$Apply)

$ErrorActionPreference = 'Stop'
$pipe = New-Object System.IO.Pipes.NamedPipeClientStream('.','ClassBuilder',
            [System.IO.Pipes.PipeDirection]::InOut)
$pipe.Connect(5000)
$rd = New-Object System.IO.StreamReader($pipe)
$wr = New-Object System.IO.StreamWriter($pipe); $wr.AutoFlush = $true
function Send($cmd, $params) {
    $msg = @{ cmd = $cmd }
    if ($params) { $msg.params = $params }
    $wr.WriteLine(($msg | ConvertTo-Json -Compress -Depth 8))
    $rd.ReadLine() | ConvertFrom-Json
}
function Cap($s) { $s.Substring(0,1).ToUpper() + $s.Substring(1) }
function Ok($r) { return ($r -and $r.ok -ne $false) }   # tolerate {ok:true,...} or bare result

# Boolean-flag MEMBERS (bare names, no prefix). Flip member type + getter
# return type (Get<Name>) + setter arg (Set<Name>, arg 0).
$members = [ordered]@{
  'Variable'                   = @('array','const','pointer','reference','pointerPointer','constPointer')
  'ExceptionSpecificationType' = @('array','const','constPointer','pointer','pointerPointer','reference')
  'Method'                     = @('const','inlineX','pure','static','virtual','untouched')
  'Member'                     = @('delete','serialize','static','mutable')
  'Class'                      = @('replace','serialize','relationMacrosLast')
  'Constructor'                = @('explicit')
  'Inherit'                    = @('virtual')
  'Relation'                   = @('critical','multi','owned','single','static','filter')
  'RelationDiagramOnlyShape'   = @('multi','owned','static')
  'DataModel'                  = @('serialize','stdAfx','undoRedo')
  'OtherType'                  = @('serializeMap')
  'ContextDeclaration'         = @('enableDefineDeclaration')
}

# Remaining int predicate METHODS (hand-written; not member getters). Flip
# return type only -- bodies already yield bool.
$methods = [ordered]@{
  'ClassDiagramShape' = @('DrawDirect')
  'ConnectionShape'   = @('IsFromAtBottom','IsFromAtLeft','IsFromAtRight','IsFromAtTop',
                          'IsToAtBottom','IsToAtLeft','IsToAtRight','IsToAtTop')
  'Method'            = @('IsDirectMethod','IsNonMacroMethod','IsNonMacroPrivateMethod',
                          'IsNonMacroProtectedMethod','IsNonMacroPublicMethod','IsNonStatic',
                          'IsNormalConstructor')
  'MacroMethod'       = @('IsNonMacroMethod')   # virtual override of Method::IsNonMacroMethod
  'Member'            = @('IsNonStatic','IsPrivate','IsProtected','IsPublic')
}

$doc = (Send 'active_doc' $null)
Write-Host "Active doc: $($doc.result.title)`n"
$fail = @(); $mc = 0; $gc = 0; $sc = 0; $rc = 0

foreach ($cls in $members.Keys) {
    foreach ($name in $members[$cls]) {
        Write-Host "member  $cls.$name (+ Get$(Cap $name)/Set$(Cap $name)) -> bool"
        $mc++
        if ($Apply) {
            $r = Send 'set_member_type' @{ class=$cls; name=$name; value='bool' }
            if (-not (Ok $r)) { $fail += "set_member_type $cls.$name : $($r.error)" }
            $r = Send 'set_method_return_type' @{ class=$cls; name=("Get"+(Cap $name)); value='bool' }
            if (Ok $r) { $gc++ } else { $fail += "getter Get$(Cap $name) on $cls : $($r.error)" }
            $r = Send 'set_argument_type' @{ class=$cls; method=("Set"+(Cap $name)); arg_index=0; value='bool' }
            if (Ok $r) { $sc++ } else { $fail += "setter Set$(Cap $name) on $cls : $($r.error)" }
        }
    }
}
foreach ($cls in $methods.Keys) {
    foreach ($mn in $methods[$cls]) {
        Write-Host "method  $cls.$mn() -> bool"
        if ($Apply) {
            $r = Send 'set_method_return_type' @{ class=$cls; name=$mn; value='bool' }
            if (Ok $r) { $rc++ } else { $fail += "set_method_return_type $cls.$mn : $($r.error)" }
        }
    }
}
$pipe.Close()

if ($Apply) {
    Write-Host "`nFLIPPED: members=$mc getters=$gc setters=$sc methods=$rc"
    if ($fail) { Write-Host "`nFAILURES ($($fail.Count)):"; $fail | ForEach-Object { Write-Host "  $_" } }
    Write-Host "`nNow: save_cb + write_source, apply bool macros, rebuild."
} else {
    Write-Host "`nWOULD flip $mc members + their getters/setters, and the predicate methods."
    Write-Host "Dry run -- re-run with -Apply."
}
