# M0a -- ClassDiagramShape family: flip Draw(CDC*,View*) -> Draw(CbPainter&,View*)
# + convert bodies, flip Draw-helpers (GetTemplateRect, DrawSelectedRect x3),
# add the base CDC forwarder. Driven over the pipe.
$pipe = New-Object System.IO.Pipes.NamedPipeClientStream('.','ClassBuilder',[System.IO.Pipes.PipeDirection]::InOut)
$pipe.Connect(4000)
$rd = New-Object System.IO.StreamReader($pipe)
$wr = New-Object System.IO.StreamWriter($pipe); $wr.AutoFlush = $true
function Send($obj){ $wr.WriteLine(($obj | ConvertTo-Json -Compress -Depth 8)); $r = $rd.ReadLine(); if ($r -notmatch '"ok":true') { Write-Output "FAIL: $($obj.params.class).$($obj.cmd)($($obj.params.method)) -> $r" } else { Write-Output "ok:   $($obj.params.class) $($obj.cmd) $($obj.params.method)" } }
function Flip($cls,$method){
    Send @{ cmd='set_argument_type'; params=@{ class=$cls; method=$method; arg_index=0; value='CbPainter&' } }
    Send @{ cmd='set_argument_name'; params=@{ class=$cls; method=$method; arg_index=0; value='painter' } }
}
function FlipBody($cls,$method,$body){ Flip $cls $method; Send @{ cmd='set_method_body'; params=@{ class=$cls; name=$method; body=$body } } }

# --- base: flip the pure virtual (no body), then add the CDC forwarder --------
Flip 'ClassDiagramShape' 'Draw'
$fwd = '{"cmd":"add_method","params":{"class":"ClassDiagramShape","name":"Draw","return_type":"void","virtual":false,"args":[{"name":"pDC","type":"CDC*"},{"name":"pCClassDiagramView","type":"CClassDiagramView*"}],"body":"    CbPainter_Cdc painter(pDC);   // MFC_CDC_BRIDGE: delete with MFC view/Track (Qt port)\r\n    Draw(painter, pCClassDiagramView);"}}'
$wr.WriteLine($fwd); $fr = $rd.ReadLine(); if ($fr -notmatch '"ok":true') { Write-Output "FAIL forwarder -> $fr" } else { Write-Output "ok:   ClassDiagramShape add_method forwarder" }

# --- MemberShape::Draw --------------------------------------------------------
FlipBody 'MemberShape' 'Draw' (@(
'    painter.Save();',
'    if (GetMember()->GetStatic())',
'        painter.SetFont(ClassDiagram::GetStaticMemberFont());',
'    else',
'        painter.SetFont(ClassDiagram::GetMemberFont());',
'    painter.SetTextAlign(TA_LEFT|TA_TOP|TA_NOUPDATECP);',
'',
'    CbString text = GetMember()->GetShapeText();',
'',
'    if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'    {',
'        painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'        painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'    }',
'    else',
'    {',
'        painter.SetTextColor(GetTextColor());',
'    }',
'',
'    painter.ExtTextOut(GetRect().left + 8, GetRect().bottom - 2,',
'                       ETO_CLIPPED, GetRect(), text);',
'',
'    painter.Restore();'
) -join "`r`n")

# --- MethodShape::Draw --------------------------------------------------------
FlipBody 'MethodShape' 'Draw' (@(
'    painter.Save();',
'    if (GetMethod()->GetStatic())',
'        painter.SetFont(ClassDiagram::GetStaticMethodFont());',
'    else',
'        painter.SetFont(ClassDiagram::GetMethodFont());',
'',
'    painter.SetTextAlign(TA_LEFT|TA_TOP|TA_NOUPDATECP);',
'',
'    if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'    {',
'        painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'        painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'    }',
'    else',
'    {',
'        painter.SetTextColor(GetTextColor());',
'    }',
'',
'    CbString text = GetMethod()->GetShapeText(VerbosityType(GetClassShape()->GetVerbosity()));',
'',
'    painter.ExtTextOut(GetRect().left + 8, GetRect().bottom - 2,',
'                       ETO_CLIPPED, GetRect(), text);',
'',
'    painter.Restore();'
) -join "`r`n")

# --- ClassShape::Draw ---------------------------------------------------------
FlipBody 'ClassShape' 'Draw' (@(
'    RecalculateRect();',
'',
'    painter.Save();',
'    painter.SetNullBrush();',
'    painter.FillSolidRect(_rect, painter.GetBkColor());',
'',
'    BaseClass::MethodIterator iMethod(GetBaseClass(), &Method::GetPure);',
'    if (++iMethod)',
'        painter.SetFont(ClassDiagram::GetAbstractClassFont());',
'    else',
'        painter.SetFont(ClassDiagram::GetClassFont());',
'    painter.SetTextAlign(TA_CENTER|TA_TOP|TA_NOUPDATECP);',
'    COLORREF oldBkColor = painter.GetBkColor();',
'    UINT options = ETO_CLIPPED;',
'',
'    SelectedClassDiagramShape* pSelectedClassDiagramShape = FindSelected(pCClassDiagramView);',
'    if (painter.IsScreen() && pSelectedClassDiagramShape)',
'    {',
'        painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'        painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'        options = ETO_CLIPPED | ETO_OPAQUE;',
'    }',
'    else',
'    {',
'        painter.SetTextColor(GetTextColor());',
'    }',
'',
'    CbRect clipRect = GetRect();',
'    if (clipRect.top < _line1Point1.y)',
'        clipRect.top = _line1Point1.y;',
'    painter.ExtTextOut(_rect.CenterPoint().x, GetRect().bottom - 2,',
'        options, clipRect, GetBaseClass()->Type::GetName());',
'',
'    painter.SetBkColor(oldBkColor);',
'',
'    MemberShapeIterator iMemberShape(this);',
'    while (++iMemberShape)',
'        iMemberShape->Draw(painter, pCClassDiagramView);',
'',
'    MethodShapeIterator iMethodShape(this);',
'    while (++iMethodShape)',
'        iMethodShape->Draw(painter, pCClassDiagramView);',
'',
'    int penStyle = PS_DOT;',
'    if (GetBaseClass()->IsClass())',
'        penStyle = PS_SOLID;',
'',
'    painter.SetTextColor(GetTextColor());',
'    painter.SetPen(penStyle, 1, GetPenColor());',
'',
'    painter.DrawRect(_rect);',
'',
'    if (GetMemberShapeCount())',
'        painter.DrawLine(_line1Point1, _line1Point2);',
'    if (GetMethodShapeCount())',
'        painter.DrawLine(_line2Point1, _line2Point2);',
'',
'    CbPoint point(GetRect().right, GetRect().bottom);',
'    CbRect templateRect(point, point);',
'    if (!GetBaseClass()->GetTemplate().IsEmpty())',
'        templateRect = GetTemplateRect(painter, TRUE);',
'    SetTemplateRect(templateRect);',
'',
'    painter.Restore();',
'',
'    if (painter.IsScreen() && pSelectedClassDiagramShape)',
'    {',
'        COLORREF color = RGB(0,255,255);',
'        if (pCClassDiagramView->GetLastSelected()->GetClassDiagramShape() == this)',
'            color = RGB(0,255,0);',
'',
'        DrawSelectedRect(painter, color);',
'    }'
) -join "`r`n")

# --- ClassShape::GetTemplateRect (helper) ------------------------------------
FlipBody 'ClassShape' 'GetTemplateRect' (@(
'    painter.Save();',
'',
'    CbString templateText = GetBaseClass()->GetTemplate();',
'    templateText.Replace(''<'', '' '');',
'    templateText.Replace(''>'', '' '');',
'',
'    painter.SetPen(PS_DASH, 1, GetPenColor());',
'    painter.SetFont(ClassDiagram::GetClassFont());',
'    painter.SetTextAlign(TA_LEFT|TA_BOTTOM|TA_NOUPDATECP);',
'',
'    CbSize textSize = painter.GetTextExtent(templateText);',
'    CbPoint point(GetRect().right-textSize.cx/2, GetRect().bottom-textSize.cy/2);',
'    CbRect rect(point, textSize);',
'    rect.NormalizeRect();',
'',
'    if (draw)',
'    {',
'        painter.ExtTextOut(rect.left, rect.top,',
'            ETO_CLIPPED | ETO_OPAQUE, rect, templateText);',
'        painter.DrawRect(rect);',
'    }',
'',
'    painter.Restore();',
'',
'    return rect;'
) -join "`r`n")

# --- ClassShape::DrawSelectedRect (helper -> DrawSelectionHandle) -------------
FlipBody 'ClassShape' 'DrawSelectedRect' (@(
'    painter.DrawSelectionHandle(GetLeftSelectedPoint(),  color);',
'    painter.DrawSelectionHandle(GetRightSelectedPoint(), color);'
) -join "`r`n")

# --- NoteShape::Draw ----------------------------------------------------------
FlipBody 'NoteShape' 'Draw' (@(
'    const int size = GetFontHeight() + 2;',
'',
'    CbRect rect = GetRect();',
'    rect.top = rect.bottom;',
'    int y = rect.bottom-2;',
'    int x = (rect.left + rect.right)/2;',
'',
'    painter.Save();',
'',
'    CFont font;',
'    font.CreateFont(GetFontHeight(), 0, 0, 0, FW_NORMAL, FALSE, FALSE, 0,',
'        ANSI_CHARSET, OUT_TT_PRECIS, CLIP_DEFAULT_PRECIS,',
'        DEFAULT_QUALITY, DEFAULT_PITCH|FF_SWISS, "Arial");',
'    painter.SetFont(&font);',
'',
'    painter.SetTextAlign(TA_CENTER|TA_TOP|TA_NOUPDATECP);',
'    painter.SetTextColor(GetTextColor());',
'',
'    CbString note = GetNote();',
'    int index = note.Find(NL);',
'    while (index != -1)',
'    {',
'        note = note.Left(index) + " " + note.Mid(index+2);',
'        index = note.Find(NL);',
'    }',
'    index = note.Find("  ");',
'    while (index != -1)',
'    {',
'        note = note.Left(index) + note.Mid(index+1);',
'        index = note.Find("  ");',
'    }',
'',
'    note.TrimLeft();',
'    note.TrimRight();',
'    int width = rect.Width() - size * 2;',
'    if (painter.GetTextExtent(note).cx > width)',
'    {',
'        CbString line;',
'        CbString lineOk;',
'',
'        index = note.FindOneOf(" \t");',
'        while (index != -1)',
'        {',
'            line += note.Left(index+1);',
'',
'            if (painter.GetTextExtent(line).cx <= width || lineOk.IsEmpty())',
'            {',
'                lineOk = line;',
'                note = note.Mid(index+1);',
'            }',
'            else',
'            {',
'                CbRect clipRect(rect.left, y-size, rect.right, y);',
'                note.TrimLeft();',
'                lineOk.TrimRight();',
'                painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, lineOk);',
'                y -= size;',
'                line.Empty();',
'                lineOk.Empty();',
'                width = rect.Width() - GetFontHeight()/2;',
'            }',
'',
'            index = note.FindOneOf(" \t\n");',
'        }',
'',
'        if (!lineOk.IsEmpty())',
'        {',
'            CbString rest = lineOk + note;',
'            if (painter.GetTextExtent(rest).cx <= width)',
'            {',
'                CbRect clipRect(rect.left, y-size, rect.right, y);',
'                painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, rest);',
'                y -= size;',
'                note.Empty();',
'            }',
'            else',
'            {',
'                CbRect clipRect(rect.left, y-size, rect.right, y);',
'                note.TrimLeft();',
'                lineOk.TrimRight();',
'                painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, lineOk);',
'                y -= size;',
'                width = rect.Width() - GetFontHeight()/2;',
'            }',
'        }',
'    }',
'',
'    if (!note.IsEmpty())',
'    {',
'        CbRect clipRect(rect.left, y-size, rect.right, y);',
'        painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, note);',
'        y -= size;',
'    }',
'    rect.top = y;',
'    if (rect.Height() < size * 2)',
'        rect.top -= size * 2 - rect.Height();',
'    SetRect(rect);',
'',
'    painter.SetPen(PS_SOLID, 1, GetPenColor());',
'    painter.DrawLine(CbPoint(rect.left, rect.top),              CbPoint(rect.right, rect.top));',
'    painter.DrawLine(CbPoint(rect.right, rect.top),             CbPoint(rect.right, rect.bottom - size));',
'    painter.DrawLine(CbPoint(rect.right, rect.bottom - size),   CbPoint(rect.right - size, rect.bottom));',
'    painter.DrawLine(CbPoint(rect.right - size, rect.bottom),   CbPoint(rect.right - size, rect.bottom - size));',
'    painter.DrawLine(CbPoint(rect.right - size, rect.bottom - size), CbPoint(rect.right, rect.bottom - size));',
'    painter.DrawLine(CbPoint(rect.right - size, rect.bottom),   CbPoint(rect.left, rect.bottom));',
'    painter.DrawLine(CbPoint(rect.left, rect.bottom),           CbPoint(rect.left, rect.top));',
'',
'    painter.SetPen(PS_DASH, 1, GetPenColor());',
'    NoteShapePointIterator iSDNoteShapePoint(this);',
'    while (++iSDNoteShapePoint)',
'    {',
'        if (!iSDNoteShapePoint.IsLast())',
'        {',
'            painter.DrawLine(',
'                Shape::CrossPoint(GetRect(), iSDNoteShapePoint->GetPoint()),',
'                iSDNoteShapePoint->GetPoint());',
'        }',
'    }',
'',
'    painter.Restore();',
'',
'    SelectedClassDiagramShape* pSelectedClassDiagramShape = FindSelected(pCClassDiagramView);',
'    if (painter.IsScreen() && pSelectedClassDiagramShape)',
'    {',
'        COLORREF color = RGB(0,255,255);',
'        if (pCClassDiagramView->GetLastSelected()->GetClassDiagramShape() == this)',
'            color = RGB(0,255,0);',
'',
'        DrawSelectedRect(painter, color);',
'    }'
) -join "`r`n")

# --- NoteShape::DrawSelectedRect (helper -> DrawSelectionHandle) --------------
FlipBody 'NoteShape' 'DrawSelectedRect' (@(
'    painter.DrawSelectionHandle(GetLeftSelectedPoint(),  color);',
'    painter.DrawSelectionHandle(GetRightSelectedPoint(), color);',
'',
'    NoteShapePointIterator iSDNoteShapePoint(this);',
'    while (++iSDNoteShapePoint)',
'        painter.DrawSelectionHandle(iSDNoteShapePoint->GetPoint(), color);'
) -join "`r`n")

# --- ConnectionShape::Draw ----------------------------------------------------
FlipBody 'ConnectionShape' 'Draw' (@(
'    ConnectionShape::ConnectionSegmentIterator iConnectionSegment(this);',
'    while (++iConnectionSegment)',
'        iConnectionSegment->Draw(painter);',
'',
'    if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'    {',
'        COLORREF color = RGB(0,255,255);',
'        if (pCClassDiagramView->GetLastSelected()->GetClassDiagramShape() == this)',
'            color = RGB(0,255,0);',
'',
'        iConnectionSegment.Reset();',
'        while (++iConnectionSegment)',
'            iConnectionSegment->DrawSelectedRect(painter, color);',
'    }'
) -join "`r`n")

# --- ConnectionSegment::DrawSelectedRect (helper -> DrawSelectionHandle) ------
FlipBody 'ConnectionSegment' 'DrawSelectedRect' (@(
'    painter.DrawSelectionHandle(GetSelectedPoint(), color);'
) -join "`r`n")

# --- InheritShape::Draw -------------------------------------------------------
FlipBody 'InheritShape' 'Draw' (@(
'    if (!GetHidden())',
'    {',
'        if (GetFromClassShape() != GetToClassShape())',
'        {',
'            painter.Save();',
'            painter.SetPen(PS_SOLID, 1, GetPenColor());',
'            painter.SetSolidBrush(GetPenColor());',
'            ConnectionShape::Draw(painter, pCClassDiagramView);',
'            painter.Restore();',
'        }',
'    }'
) -join "`r`n")

# --- RelationShape::Draw ------------------------------------------------------
FlipBody 'RelationShape' 'Draw' (@(
'    if (!GetHidden())',
'    {',
'        painter.Save();',
'',
'        int width = 1;',
'        if (GetRelation()->GetStatic())',
'            width = 4;',
'        painter.SetPen(PS_SOLID, width, GetPenColor());',
'        painter.SetSolidBrush(GetPenColor());',
'',
'        ConnectionShape::Draw(painter, pCClassDiagramView);',
'',
'        painter.SetFont(ClassDiagram::GetRelationFont());',
'        painter.SetTextAlign(TA_LEFT|TA_BOTTOM|TA_NOUPDATECP);',
'',
'        if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'        {',
'            painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'            painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'        }',
'        else',
'        {',
'            painter.SetTextColor(GetTextColor());',
'        }',
'',
'        CbRect rect = GetRect();',
'',
'        if (GetVerbosity())',
'        {',
'            CbRect fromNameRect(_fromNamePoint, painter.GetTextExtent(GetRelation()->GetFromName()));',
'            rect *= fromNameRect;',
'            CbRect toNameRect(_toNamePoint, painter.GetTextExtent(GetRelation()->GetToName()));',
'            rect *= toNameRect;',
'            painter.TextOut(_fromNamePoint.x, _fromNamePoint.y, GetRelation()->GetFromName());',
'            painter.TextOut(_toNamePoint.x, _toNamePoint.y, GetRelation()->GetToName());',
'        }',
'',
'        CbRect fromUmlRect(_fromUmlPoint, painter.GetTextExtent(GetUmlFrom()));',
'        rect *= fromUmlRect;',
'        CbRect toUmlRect(_toUmlPoint, painter.GetTextExtent(GetUmlTo()));',
'        rect *= toUmlRect;',
'        painter.TextOut(_fromUmlPoint.x, _fromUmlPoint.y, GetUmlFrom());',
'        painter.TextOut(_toUmlPoint.x, _toUmlPoint.y, GetUmlTo());',
'',
'        if (rect != GetRect())',
'            SetRect(rect);',
'',
'        painter.Restore();',
'    }'
) -join "`r`n")

# --- DependencyShape::Draw ----------------------------------------------------
FlipBody 'DependencyShape' 'Draw' (@(
'    if (!GetHidden())',
'    {',
'        painter.Save();',
'',
'        painter.SetPen(PS_DASH, 1, GetPenColor());',
'        painter.SetSolidBrush(GetPenColor());',
'',
'        ConnectionShape::Draw(painter, pCClassDiagramView);',
'',
'        painter.SetFont(ClassDiagram::GetRelationFont());',
'        painter.SetTextAlign(TA_LEFT|TA_BOTTOM|TA_NOUPDATECP);',
'',
'        if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'        {',
'            painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'            painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'        }',
'        else',
'        {',
'            painter.SetTextColor(GetTextColor());',
'        }',
'',
'        CbRect rect = GetRect();',
'',
'        if (!GetStereotypeString().IsEmpty())',
'        {',
'            CbRect stereotypeRect(_stereotypePoint, painter.GetTextExtent(GetStereotypeString()));',
'            rect *= stereotypeRect;',
'            painter.TextOut(_stereotypePoint.x, _stereotypePoint.y, GetStereotypeString());',
'        }',
'',
'        if (!_name.IsEmpty())',
'        {',
'            CbRect nameRect(_namePoint, painter.GetTextExtent(_name));',
'            rect *= nameRect;',
'            painter.TextOut(_namePoint.x, _namePoint.y, _name);',
'        }',
'',
'        if (rect != GetRect())',
'            SetRect(rect);',
'',
'        painter.Restore();',
'    }'
) -join "`r`n")

# --- RelationDiagramOnlyShape::Draw ------------------------------------------
FlipBody 'RelationDiagramOnlyShape' 'Draw' (@(
'    if (!GetHidden())',
'    {',
'        painter.Save();',
'',
'        int width = 1;',
'        if (GetStatic())',
'            width = 4;',
'        painter.SetPen(PS_SOLID, width, GetPenColor());',
'        painter.SetSolidBrush(GetPenColor());',
'',
'        ConnectionShape::Draw(painter, pCClassDiagramView);',
'',
'        painter.SetFont(ClassDiagram::GetRelationFont());',
'        painter.SetTextAlign(TA_LEFT|TA_BOTTOM|TA_NOUPDATECP);',
'',
'        if (painter.IsScreen() && FindSelected(pCClassDiagramView))',
'        {',
'            painter.SetTextColor(::GetSysColor(COLOR_HIGHLIGHTTEXT));',
'            painter.SetBkColor(::GetSysColor(COLOR_HIGHLIGHT));',
'        }',
'        else',
'        {',
'            painter.SetTextColor(GetTextColor());',
'        }',
'',
'        CbRect rect = GetRect();',
'',
'        if (!GetFromName().IsEmpty())',
'        {',
'            CbRect fromNameRect(_fromNamePoint, painter.GetTextExtent(GetFromName()));',
'            rect *= fromNameRect;',
'            painter.TextOut(_fromNamePoint.x, _fromNamePoint.y, GetFromName());',
'        }',
'',
'        if (!GetToName().IsEmpty())',
'        {',
'            CbRect toNameRect(_toNamePoint, painter.GetTextExtent(GetToName()));',
'            rect *= toNameRect;',
'            painter.TextOut(_toNamePoint.x, _toNamePoint.y, GetToName());',
'        }',
'',
'        if (!GetUmlFrom().IsEmpty())',
'        {',
'            CbRect fromUmlRect(_fromUmlPoint, painter.GetTextExtent(GetUmlFrom()));',
'            rect *= fromUmlRect;',
'            painter.TextOut(_fromUmlPoint.x, _fromUmlPoint.y, GetUmlFrom());',
'        }',
'',
'        if (!GetUmlTo().IsEmpty())',
'        {',
'            CbRect toUmlRect(_toUmlPoint, painter.GetTextExtent(GetUmlTo()));',
'            rect *= toUmlRect;',
'            painter.TextOut(_toUmlPoint.x, _toUmlPoint.y, GetUmlTo());',
'        }',
'',
'        if (rect != GetRect())',
'            SetRect(rect);',
'',
'        painter.Restore();',
'    }'
) -join "`r`n")

# Flush model -> disk
Send @{ cmd='write_source'; params=@{ modified_only=$true } }
$pipe.Close()
Write-Output "DONE"
