# Carry the SDNoteShape newline-honouring text layout into ClassDiagram NoteShape::Draw.
$pipe = New-Object System.IO.Pipes.NamedPipeClientStream('.','ClassBuilder',[System.IO.Pipes.PipeDirection]::InOut)
$pipe.Connect(4000)
$rd = New-Object System.IO.StreamReader($pipe); $wr = New-Object System.IO.StreamWriter($pipe); $wr.AutoFlush=$true
function Send($obj){ $wr.WriteLine(($obj | ConvertTo-Json -Compress -Depth 8)); $r=$rd.ReadLine(); if ($r -match '"ok":true') { Write-Output "ok:   $($obj.cmd)" } else { Write-Output "FAIL: $($obj.cmd) -> $r" } }

$body = @(
'    const int size = GetFontHeight() + 2;',
'',
'    CbRect rect = GetRect();',
'    rect.top = rect.bottom;',
'    int y = rect.bottom-2;',
'    int x = (rect.left + rect.right)/2;',
'',
'    int save = painter.Save();',
'',
'    CFont font;',
'    font.CreateFont(GetFontHeight(), 0, 0, 0, FW_NORMAL, FALSE, FALSE, 0,',
'        ANSI_CHARSET, OUT_TT_PRECIS, CLIP_DEFAULT_PRECIS,',
'        DEFAULT_QUALITY, DEFAULT_PITCH|FF_SWISS, "Arial");',
'    painter.SetFont(&font);',
'',
'    painter.SetTextAlign(TA_CENTER|TA_TOP|TA_NOUPDATECP);',
'    painter.SetTextColor(GetTextColor());',
'',
'    // Honour explicit newlines (NL) as HARD breaks (carried over from',
'    // SDNoteShape::Draw); each NL-segment is word-wrapped to the box width,',
'    // blank paragraphs advance one line once content has started.',
'    CbString remaining = GetNote();',
'    int width = rect.Width() - size * 2;',
'    const int yStart = y;',
'    BOOL moreSegments = TRUE;',
'    while (moreSegments)',
'    {',
'        int nlIndex = remaining.Find(NL);',
'        CbString note;',
'        if (nlIndex == -1)',
'        {',
'            note = remaining;',
'            moreSegments = FALSE;',
'        }',
'        else',
'        {',
'            note = remaining.Left(nlIndex);',
'            remaining = remaining.Mid(nlIndex + 2);',
'        }',
'',
'        int index = note.Find("  ");',
'        while (index != -1)',
'        {',
'            note = note.Left(index) + note.Mid(index+1);',
'            index = note.Find("  ");',
'        }',
'',
'        note.TrimLeft();',
'        note.TrimRight();',
'        const BOOL segmentWasEmpty = note.IsEmpty();',
'        if (painter.GetTextExtent(note).cx > width)',
'        {',
'            CbString line;',
'            CbString lineOk;',
'',
'            index = note.FindOneOf(" \t");',
'            while (index != -1)',
'            {',
'                line += note.Left(index+1);',
'',
'                if (painter.GetTextExtent(line).cx <= width || lineOk.IsEmpty())',
'                {',
'                    lineOk = line;',
'                    note = note.Mid(index+1);',
'                }',
'                else',
'                {',
'                    CbRect clipRect(rect.left, y-size, rect.right, y);',
'                    note.TrimLeft();',
'                    lineOk.TrimRight();',
'                    painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, lineOk);',
'                    y -= size;',
'                    line.Empty();',
'                    lineOk.Empty();',
'                    width = rect.Width() - GetFontHeight()/2;',
'                }',
'',
'                index = note.FindOneOf(" \t");',
'            }',
'',
'            if (!lineOk.IsEmpty())',
'            {',
'                CbString rest = lineOk + note;',
'                if (painter.GetTextExtent(rest).cx <= width)',
'                {',
'                    CbRect clipRect(rect.left, y-size, rect.right, y);',
'                    painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, rest);',
'                    y -= size;',
'                    note.Empty();',
'                }',
'                else',
'                {',
'                    CbRect clipRect(rect.left, y-size, rect.right, y);',
'                    note.TrimLeft();',
'                    lineOk.TrimRight();',
'                    painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, lineOk);',
'                    y -= size;',
'                    width = rect.Width() - GetFontHeight()/2;',
'                }',
'            }',
'        }',
'',
'        if (!note.IsEmpty())',
'        {',
'            CbRect clipRect(rect.left, y-size, rect.right, y);',
'            painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, note);',
'            y -= size;',
'        }',
'        else if (segmentWasEmpty && y != yStart)',
'        {',
'            CbRect clipRect(rect.left, y-size, rect.right, y);',
'            painter.ExtTextOut(x, y, ETO_CLIPPED | ETO_OPAQUE, clipRect, CbString(""));',
'            y -= size;',
'        }',
'    }',
'    rect.top = y;',
'    if (rect.Height() < size * 2)',
'    {',
'        rect.top -= size * 2 - rect.Height();',
'    }',
'    SetRect(rect);',
'',
'    painter.SetPen(PS_SOLID, 1, GetPenColor());',
'    painter.DrawLine(CbPoint(rect.left, rect.top),                  CbPoint(rect.right, rect.top));',
'    painter.DrawLine(CbPoint(rect.right, rect.top),                 CbPoint(rect.right, rect.bottom-size));',
'    painter.DrawLine(CbPoint(rect.right, rect.bottom-size),         CbPoint(rect.right-size, rect.bottom));',
'    painter.DrawLine(CbPoint(rect.right-size, rect.bottom),         CbPoint(rect.right-size, rect.bottom-size));',
'    painter.DrawLine(CbPoint(rect.right-size, rect.bottom-size),    CbPoint(rect.right, rect.bottom-size));',
'    painter.DrawLine(CbPoint(rect.right-size, rect.bottom),         CbPoint(rect.left, rect.bottom));',
'    painter.DrawLine(CbPoint(rect.left, rect.bottom),               CbPoint(rect.left, rect.top));',
'',
'    painter.SetPen(PS_DASH, 1, GetPenColor());',
'    NoteShapePointIterator iSDNoteShapePoint(this);',
'    while (++iSDNoteShapePoint)',
'    {',
'        if (!iSDNoteShapePoint.IsLast())',
'        {',
'            painter.DrawLine(',
'                Shape::CrossPoint(GetRect(), iSDNoteShapePoint->GetPoint()),',
'                iSDNoteShapePoint->GetPoint());',
'        }',
'    }',
'',
'    painter.Restore(save);',
'',
'    SelectedClassDiagramShape* pSelectedClassDiagramShape = FindSelected(pCClassDiagramView);',
'    if (painter.IsScreen() && pSelectedClassDiagramShape)',
'    {',
'        COLORREF color = RGB(0,255,255);',
'        if (pCClassDiagramView->GetLastSelected()->GetClassDiagramShape() == this)',
'        {',
'            color = RGB(0,255,0);',
'        }',
'',
'        DrawSelectedRect(painter, color);',
'    }'
) -join "`r`n"

Send @{ cmd='set_method_body'; params=@{ class='NoteShape'; name='Draw'; body=$body } }
Send @{ cmd='write_source'; params=@{ modified_only=$true } }
$pipe.Close()
Write-Output "DONE"
